-- таблица пользователей
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- таблица вещей
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(256) NOT NULL,
  description VARCHAR(256) NOT NULL,
  owner_id BIGINT NOT NULL,
  available BOOLEAN NOT NULL,
  count_of_rent BIGINT NOT NULL,
  last_rent TIMESTAMP NOT NULL,
  next_rent TIMESTAMP NOT NULL,
  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_items_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- таблица вещей которые пользователь имеет в распоряжении
CREATE TABLE IF NOT EXISTS demand_items (
  item_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT pk_demand_items PRIMARY KEY (item_id, user_id),
  CONSTRAINT fk_demand_items_to_items FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_demand_items_to_users FOREIGN KEY (user_id) REFERENCES users(id)
);

-- таблица вещей которые пользователь может предоставить в аренду
CREATE TABLE IF NOT EXISTS supply_items (
  item_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT pk_supply_items PRIMARY KEY (item_id, user_id),
  CONSTRAINT fk_supply_items_to_items FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_supply_items_to_users FOREIGN KEY (user_id) REFERENCES users(id)
);

-- таблица отзывов
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  item_id BIGINT NOT NULL,
  comment VARCHAR(256) NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id),
  CONSTRAINT fk_comments_to_item FOREIGN KEY (item_id) REFERENCES items(id)
);

-- таблица запросов вещей
CREATE TABLE IF NOT EXISTS request_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  item_id BIGINT NOT NULL,
  status VARCHAR(7) NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT pk_request_items PRIMARY KEY (id),
  CONSTRAINT fk_request_items_to_item FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_request_items_to_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- таблица бронирования вещей
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  status VARCHAR(8) NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  CONSTRAINT pk_booking PRIMARY KEY (id),
  CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) REFERENCES users(id)
);
